### ISSUE TITLE
Schema Registry Cluster support

### ISSUE THREAD

**Issue by jonathangold** [crossplane-contrib/provider-confluent#12]
### What problem are you facing?
I would like to deploy a "confluent_schema_registry_cluster" via crossplane, but the resource is not currently available in the provider. 

### How could Crossplane help solve your problem?
By generating a new version of the provider which includes the schema registry cluster resource.

**Comment by jaylevin** [comment]
@jonathangold This resource was released in the latest version, v0.4.2. Let us know any feedback or additional suggestions!
